<?php

/**
 * HsHrEmpBasicsalaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HsHrEmpBasicsalaryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HsHrEmpBasicsalaryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HsHrEmpBasicsalary');
    }
    
     public static function  getPayslipForMonth($empno,$month){
             $q = Doctrine_Query::create()
                            ->from('HsHrEmpBasicsalary')
                         ->where(" `emp_number`=$empno")
  ->andWhere("DATE_FORMAT(`payslipdate`,'%m/%Y') like '$month'");
            $q->execute();
        
      return $q->fetchOne();
    }
    
         public static function  getEmpBasicSalary($empno){
             HsHrEmpBasicsalary::$_null;
             $q = Doctrine_Query::create()
                            ->from('HsHrEmpBasicsalary')
                         ->where(" `emp_number`=$empno")
  ->andWhere("salary_component like '%Basic%' ");
            $q->execute();
        
 $salary=$q->fetchOne();
 if(is_object($salary)){
 return $salary->getEbsalBasicSalary();
 }else{
     return 0;
 }
    }
	
	 public static function  getSalaryCode($empno){
             HsHrEmpBasicsalary::$_null;
             $q = Doctrine_Query::create()
                            ->from('HsHrEmpBasicsalary')
                         ->where(" `emp_number`=$empno")
  ->andWhere("salary_component like '%Basic%' ");
            $q->execute();
        
 $salary=$q->fetchOne();
 if(is_object($salary)){
 return $salary->getSalGrdCode();
 }else{
     return 0;
 }
    }
    
     public static function  getEmpHouseAllowance($empno){
             HsHrEmpBasicsalary::$_null;
             $q = Doctrine_Query::create()
                            ->from('HsHrEmpBasicsalary')
                         ->where(" `emp_number`=$empno")
  ->andWhere("salary_component like '%House Allowance%' ");
            $q->execute();
 $salary=$q->fetchOne();
 if(is_object($salary)){
 return $salary->getEbsalBasicSalary();
 }else{
     return 0;
 }
    }
    
     public static function getEmpDailyPay($empno) {
  
        $salary = HsHrEmpBasicsalaryTable::getEmpBasicSalary($empno);
        $dailypay = round(($salary * 12) / 365);
        return round($dailypay,2);
    }
    
}