<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmProjectAdmin', 'doctrine');

/**
 * BaseOhrmProjectAdmin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $project_id
 * @property integer $emp_number
 * 
 * @method integer          getProjectId()  Returns the current record's "project_id" value
 * @method integer          getEmpNumber()  Returns the current record's "emp_number" value
 * @method OhrmProjectAdmin setProjectId()  Sets the current record's "project_id" value
 * @method OhrmProjectAdmin setEmpNumber()  Sets the current record's "emp_number" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmProjectAdmin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_project_admin');
        $this->hasColumn('project_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}