<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmLeaveRequest', 'doctrine');

/**
 * BaseOhrmLeaveRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $leave_type_id
 * @property date $date_applied
 * @property integer $emp_number
 * @property string $comments
 * 
 * @method integer          getId()            Returns the current record's "id" value
 * @method integer          getLeaveTypeId()   Returns the current record's "leave_type_id" value
 * @method date             getDateApplied()   Returns the current record's "date_applied" value
 * @method integer          getEmpNumber()     Returns the current record's "emp_number" value
 * @method string           getComments()      Returns the current record's "comments" value
 * @method OhrmLeaveRequest setId()            Sets the current record's "id" value
 * @method OhrmLeaveRequest setLeaveTypeId()   Sets the current record's "leave_type_id" value
 * @method OhrmLeaveRequest setDateApplied()   Sets the current record's "date_applied" value
 * @method OhrmLeaveRequest setEmpNumber()     Sets the current record's "emp_number" value
 * @method OhrmLeaveRequest setComments()      Sets the current record's "comments" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmLeaveRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_leave_request');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('leave_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date_applied', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('comments', 'string', 256, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 256,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}