<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmDatapointType', 'doctrine');

/**
 * BaseOhrmDatapointType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $action_class
 * 
 * @method integer           getId()           Returns the current record's "id" value
 * @method string            getName()         Returns the current record's "name" value
 * @method string            getActionClass()  Returns the current record's "action_class" value
 * @method OhrmDatapointType setId()           Sets the current record's "id" value
 * @method OhrmDatapointType setName()         Sets the current record's "name" value
 * @method OhrmDatapointType setActionClass()  Sets the current record's "action_class" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmDatapointType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_datapoint_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('action_class', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}