<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmPayGradeCurrency', 'doctrine');

/**
 * BaseOhrmPayGradeCurrency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $pay_grade_id
 * @property string $currency_id
 * @property string $salary_component
 * @property float $min_salary
 * @property float $max_salary
 * 
 * @method integer              getId()               Returns the current record's "id" value
 * @method integer              getPayGradeId()       Returns the current record's "pay_grade_id" value
 * @method string               getCurrencyId()       Returns the current record's "currency_id" value
 * @method string               getSalaryComponent()  Returns the current record's "salary_component" value
 * @method float                getMinSalary()        Returns the current record's "min_salary" value
 * @method float                getMaxSalary()        Returns the current record's "max_salary" value
 * @method OhrmPayGradeCurrency setId()               Sets the current record's "id" value
 * @method OhrmPayGradeCurrency setPayGradeId()       Sets the current record's "pay_grade_id" value
 * @method OhrmPayGradeCurrency setCurrencyId()       Sets the current record's "currency_id" value
 * @method OhrmPayGradeCurrency setSalaryComponent()  Sets the current record's "salary_component" value
 * @method OhrmPayGradeCurrency setMinSalary()        Sets the current record's "min_salary" value
 * @method OhrmPayGradeCurrency setMaxSalary()        Sets the current record's "max_salary" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmPayGradeCurrency extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_pay_grade_currency');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('pay_grade_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('currency_id', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
        $this->hasColumn('salary_component', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('min_salary', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('max_salary', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}