<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmDataGroupScreen', 'doctrine');

/**
 * BaseOhrmDataGroupScreen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $data_group_id
 * @property integer $screen_id
 * @property integer $permission
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getDataGroupId()   Returns the current record's "data_group_id" value
 * @method integer             getScreenId()      Returns the current record's "screen_id" value
 * @method integer             getPermission()    Returns the current record's "permission" value
 * @method OhrmDataGroupScreen setId()            Sets the current record's "id" value
 * @method OhrmDataGroupScreen setDataGroupId()   Sets the current record's "data_group_id" value
 * @method OhrmDataGroupScreen setScreenId()      Sets the current record's "screen_id" value
 * @method OhrmDataGroupScreen setPermission()    Sets the current record's "permission" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmDataGroupScreen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_data_group_screen');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('data_group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('screen_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('permission', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}