<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OhrmEmployeeWorkShift', 'doctrine');

/**
 * BaseOhrmEmployeeWorkShift
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $work_shift_id
 * @property integer $emp_number
 * 
 * @method integer               getWorkShiftId()   Returns the current record's "work_shift_id" value
 * @method integer               getEmpNumber()     Returns the current record's "emp_number" value
 * @method OhrmEmployeeWorkShift setWorkShiftId()   Sets the current record's "work_shift_id" value
 * @method OhrmEmployeeWorkShift setEmpNumber()     Sets the current record's "emp_number" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOhrmEmployeeWorkShift extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ohrm_employee_work_shift');
        $this->hasColumn('work_shift_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}