<?php

/**
 * OhrmPayrollconfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OhrmPayrollconfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OhrmPayrollconfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OhrmPayrollconfig');
    }
}