<?php

/**
 * BaseDocumentsCheckList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $emp_number
 * @property string $remarks
 * @property string $document
 * @property integer $status

 * 
 * @method integer     getEmpNumber()  Returns the current record's "emp_number" value
 * @method string     getRemarks()      Returns the current record's "seqno" value
 * @method string      getDocument()       Returns the current record's "name" value
 * @method integer       getStatus()        Returns the current record's "dob" value
 
 * @method DocumentsChecklist setEmpNumber()      Sets the current record's "seqno" value
 * @method DocumentsChecklist setRemarks()       Sets the current record's "name" value
 * @method DocumentsChecklist setDocument()        Sets the current record's "dob" value
 * @method DocumentsChecklist setStatus()   Sets the current record's "Employee" value
 * 
 * @package    orangehrm
 * @subpackage model\base
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentsChecklist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documents_checklist');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
         $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
      
        $this->hasColumn('remarks', 'string',255, array(
             'type' => 'string',
             'default' => '',
             'length' => 255,
             ));
         $this->hasColumn('document', 'string',255, array(
             'type' => 'string',
             'default' => '',
             'length' => 255,
             ));
    }

 
}